//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace ESFA.DC.ILR.Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="ESFA/ILR/2018-19", IsNullable=false)]
    public partial class Message {
        
        private MessageHeader headerField;
        
        private MessageSourceFile[] sourceFilesField;
        
        private MessageLearningProvider learningProviderField;
        
        private MessageLearner[] learnerField;
        
        private MessageLearnerDestinationandProgression[] learnerDestinationandProgressionField;
        
        /// <remarks/>
        public MessageHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SourceFile", IsNullable=false)]
        public MessageSourceFile[] SourceFiles {
            get {
                return this.sourceFilesField;
            }
            set {
                this.sourceFilesField = value;
            }
        }
        
        /// <remarks/>
        public MessageLearningProvider LearningProvider {
            get {
                return this.learningProviderField;
            }
            set {
                this.learningProviderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Learner")]
        public MessageLearner[] Learner {
            get {
                return this.learnerField;
            }
            set {
                this.learnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LearnerDestinationandProgression")]
        public MessageLearnerDestinationandProgression[] LearnerDestinationandProgression {
            get {
                return this.learnerDestinationandProgressionField;
            }
            set {
                this.learnerDestinationandProgressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageHeader {
        
        private MessageHeaderCollectionDetails collectionDetailsField;
        
        private MessageHeaderSource sourceField;
        
        /// <remarks/>
        public MessageHeaderCollectionDetails CollectionDetails {
            get {
                return this.collectionDetailsField;
            }
            set {
                this.collectionDetailsField = value;
            }
        }
        
        /// <remarks/>
        public MessageHeaderSource Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageHeaderCollectionDetails {
        
        private MessageHeaderCollectionDetailsCollection collectionField;
        
        private MessageHeaderCollectionDetailsYear yearField;
        
        private System.DateTime filePreparationDateField;
        
        /// <remarks/>
        public MessageHeaderCollectionDetailsCollection Collection {
            get {
                return this.collectionField;
            }
            set {
                this.collectionField = value;
            }
        }
        
        /// <remarks/>
        public MessageHeaderCollectionDetailsYear Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FilePreparationDate {
            get {
                return this.filePreparationDateField;
            }
            set {
                this.filePreparationDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public enum MessageHeaderCollectionDetailsCollection {
        
        /// <remarks/>
        ILR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public enum MessageHeaderCollectionDetailsYear {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1819")]
        Item1819,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageHeaderSource {
        
        private MessageHeaderSourceProtectiveMarking protectiveMarkingField;
        
        private int uKPRNField;
        
        private string softwareSupplierField;
        
        private string softwarePackageField;
        
        private string releaseField;
        
        private string serialNoField;
        
        private System.DateTime dateTimeField;
        
        private string referenceDataField;
        
        private string componentSetVersionField;
        
        /// <remarks/>
        public MessageHeaderSourceProtectiveMarking ProtectiveMarking {
            get {
                return this.protectiveMarkingField;
            }
            set {
                this.protectiveMarkingField = value;
            }
        }
        
        /// <remarks/>
        public int UKPRN {
            get {
                return this.uKPRNField;
            }
            set {
                this.uKPRNField = value;
            }
        }
        
        /// <remarks/>
        public string SoftwareSupplier {
            get {
                return this.softwareSupplierField;
            }
            set {
                this.softwareSupplierField = value;
            }
        }
        
        /// <remarks/>
        public string SoftwarePackage {
            get {
                return this.softwarePackageField;
            }
            set {
                this.softwarePackageField = value;
            }
        }
        
        /// <remarks/>
        public string Release {
            get {
                return this.releaseField;
            }
            set {
                this.releaseField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceData {
            get {
                return this.referenceDataField;
            }
            set {
                this.referenceDataField = value;
            }
        }
        
        /// <remarks/>
        public string ComponentSetVersion {
            get {
                return this.componentSetVersionField;
            }
            set {
                this.componentSetVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public enum MessageHeaderSourceProtectiveMarking {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OFFICIAL-SENSITIVE-Personal")]
        OFFICIALSENSITIVEPersonal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageSourceFile {
        
        private string sourceFileNameField;
        
        private System.DateTime filePreparationDateField;
        
        private string softwareSupplierField;
        
        private string softwarePackageField;
        
        private string releaseField;
        
        private string serialNoField;
        
        private System.DateTime dateTimeField;
        
        private bool dateTimeFieldSpecified;
        
        /// <remarks/>
        public string SourceFileName {
            get {
                return this.sourceFileNameField;
            }
            set {
                this.sourceFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FilePreparationDate {
            get {
                return this.filePreparationDateField;
            }
            set {
                this.filePreparationDateField = value;
            }
        }
        
        /// <remarks/>
        public string SoftwareSupplier {
            get {
                return this.softwareSupplierField;
            }
            set {
                this.softwareSupplierField = value;
            }
        }
        
        /// <remarks/>
        public string SoftwarePackage {
            get {
                return this.softwarePackageField;
            }
            set {
                this.softwarePackageField = value;
            }
        }
        
        /// <remarks/>
        public string Release {
            get {
                return this.releaseField;
            }
            set {
                this.releaseField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateTimeSpecified {
            get {
                return this.dateTimeFieldSpecified;
            }
            set {
                this.dateTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearningProvider {
        
        private int uKPRNField;
        
        /// <remarks/>
        public int UKPRN {
            get {
                return this.uKPRNField;
            }
            set {
                this.uKPRNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearner {
        
        private string learnRefNumberField;
        
        private string prevLearnRefNumberField;
        
        private int prevUKPRNField;
        
        private bool prevUKPRNFieldSpecified;
        
        private int pMUKPRNField;
        
        private bool pMUKPRNFieldSpecified;
        
        private string campIdField;
        
        private long uLNField;
        
        private string familyNameField;
        
        private string givenNamesField;
        
        private System.DateTime dateOfBirthField;
        
        private bool dateOfBirthFieldSpecified;
        
        private int ethnicityField;
        
        private string sexField;
        
        private int lLDDHealthProbField;
        
        private string nINumberField;
        
        private int priorAttainField;
        
        private bool priorAttainFieldSpecified;
        
        private int accomField;
        
        private bool accomFieldSpecified;
        
        private int aLSCostField;
        
        private bool aLSCostFieldSpecified;
        
        private int planLearnHoursField;
        
        private bool planLearnHoursFieldSpecified;
        
        private int planEEPHoursField;
        
        private bool planEEPHoursFieldSpecified;
        
        private string mathGradeField;
        
        private string engGradeField;
        
        private string postcodePriorField;
        
        private string postcodeField;
        
        private string addLine1Field;
        
        private string addLine2Field;
        
        private string addLine3Field;
        
        private string addLine4Field;
        
        private string telNoField;
        
        private string emailField;
        
        private int oTJHoursField;
        
        private bool oTJHoursFieldSpecified;
        
        private MessageLearnerContactPreference[] contactPreferenceField;
        
        private MessageLearnerLLDDandHealthProblem[] lLDDandHealthProblemField;
        
        private MessageLearnerLearnerFAM[] learnerFAMField;
        
        private MessageLearnerProviderSpecLearnerMonitoring[] providerSpecLearnerMonitoringField;
        
        private MessageLearnerLearnerEmploymentStatus[] learnerEmploymentStatusField;
        
        private MessageLearnerLearnerHE learnerHEField;
        
        private MessageLearnerLearningDelivery[] learningDeliveryField;
        
        /// <remarks/>
        public string LearnRefNumber {
            get {
                return this.learnRefNumberField;
            }
            set {
                this.learnRefNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PrevLearnRefNumber {
            get {
                return this.prevLearnRefNumberField;
            }
            set {
                this.prevLearnRefNumberField = value;
            }
        }
        
        /// <remarks/>
        public int PrevUKPRN {
            get {
                return this.prevUKPRNField;
            }
            set {
                this.prevUKPRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrevUKPRNSpecified {
            get {
                return this.prevUKPRNFieldSpecified;
            }
            set {
                this.prevUKPRNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PMUKPRN {
            get {
                return this.pMUKPRNField;
            }
            set {
                this.pMUKPRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PMUKPRNSpecified {
            get {
                return this.pMUKPRNFieldSpecified;
            }
            set {
                this.pMUKPRNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CampId {
            get {
                return this.campIdField;
            }
            set {
                this.campIdField = value;
            }
        }
        
        /// <remarks/>
        public long ULN {
            get {
                return this.uLNField;
            }
            set {
                this.uLNField = value;
            }
        }
        
        /// <remarks/>
        public string FamilyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        public string GivenNames {
            get {
                return this.givenNamesField;
            }
            set {
                this.givenNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfBirthSpecified {
            get {
                return this.dateOfBirthFieldSpecified;
            }
            set {
                this.dateOfBirthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Ethnicity {
            get {
                return this.ethnicityField;
            }
            set {
                this.ethnicityField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public int LLDDHealthProb {
            get {
                return this.lLDDHealthProbField;
            }
            set {
                this.lLDDHealthProbField = value;
            }
        }
        
        /// <remarks/>
        public string NINumber {
            get {
                return this.nINumberField;
            }
            set {
                this.nINumberField = value;
            }
        }
        
        /// <remarks/>
        public int PriorAttain {
            get {
                return this.priorAttainField;
            }
            set {
                this.priorAttainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriorAttainSpecified {
            get {
                return this.priorAttainFieldSpecified;
            }
            set {
                this.priorAttainFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Accom {
            get {
                return this.accomField;
            }
            set {
                this.accomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccomSpecified {
            get {
                return this.accomFieldSpecified;
            }
            set {
                this.accomFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ALSCost {
            get {
                return this.aLSCostField;
            }
            set {
                this.aLSCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ALSCostSpecified {
            get {
                return this.aLSCostFieldSpecified;
            }
            set {
                this.aLSCostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PlanLearnHours {
            get {
                return this.planLearnHoursField;
            }
            set {
                this.planLearnHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlanLearnHoursSpecified {
            get {
                return this.planLearnHoursFieldSpecified;
            }
            set {
                this.planLearnHoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PlanEEPHours {
            get {
                return this.planEEPHoursField;
            }
            set {
                this.planEEPHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlanEEPHoursSpecified {
            get {
                return this.planEEPHoursFieldSpecified;
            }
            set {
                this.planEEPHoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MathGrade {
            get {
                return this.mathGradeField;
            }
            set {
                this.mathGradeField = value;
            }
        }
        
        /// <remarks/>
        public string EngGrade {
            get {
                return this.engGradeField;
            }
            set {
                this.engGradeField = value;
            }
        }
        
        /// <remarks/>
        public string PostcodePrior {
            get {
                return this.postcodePriorField;
            }
            set {
                this.postcodePriorField = value;
            }
        }
        
        /// <remarks/>
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public string AddLine1 {
            get {
                return this.addLine1Field;
            }
            set {
                this.addLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddLine2 {
            get {
                return this.addLine2Field;
            }
            set {
                this.addLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string AddLine3 {
            get {
                return this.addLine3Field;
            }
            set {
                this.addLine3Field = value;
            }
        }
        
        /// <remarks/>
        public string AddLine4 {
            get {
                return this.addLine4Field;
            }
            set {
                this.addLine4Field = value;
            }
        }
        
        /// <remarks/>
        public string TelNo {
            get {
                return this.telNoField;
            }
            set {
                this.telNoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int OTJHours {
            get {
                return this.oTJHoursField;
            }
            set {
                this.oTJHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OTJHoursSpecified {
            get {
                return this.oTJHoursFieldSpecified;
            }
            set {
                this.oTJHoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactPreference")]
        public MessageLearnerContactPreference[] ContactPreference {
            get {
                return this.contactPreferenceField;
            }
            set {
                this.contactPreferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LLDDandHealthProblem")]
        public MessageLearnerLLDDandHealthProblem[] LLDDandHealthProblem {
            get {
                return this.lLDDandHealthProblemField;
            }
            set {
                this.lLDDandHealthProblemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LearnerFAM")]
        public MessageLearnerLearnerFAM[] LearnerFAM {
            get {
                return this.learnerFAMField;
            }
            set {
                this.learnerFAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProviderSpecLearnerMonitoring")]
        public MessageLearnerProviderSpecLearnerMonitoring[] ProviderSpecLearnerMonitoring {
            get {
                return this.providerSpecLearnerMonitoringField;
            }
            set {
                this.providerSpecLearnerMonitoringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LearnerEmploymentStatus")]
        public MessageLearnerLearnerEmploymentStatus[] LearnerEmploymentStatus {
            get {
                return this.learnerEmploymentStatusField;
            }
            set {
                this.learnerEmploymentStatusField = value;
            }
        }
        
        /// <remarks/>
        public MessageLearnerLearnerHE LearnerHE {
            get {
                return this.learnerHEField;
            }
            set {
                this.learnerHEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LearningDelivery")]
        public MessageLearnerLearningDelivery[] LearningDelivery {
            get {
                return this.learningDeliveryField;
            }
            set {
                this.learningDeliveryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerContactPreference {
        
        private string contPrefTypeField;
        
        private int contPrefCodeField;
        
        /// <remarks/>
        public string ContPrefType {
            get {
                return this.contPrefTypeField;
            }
            set {
                this.contPrefTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ContPrefCode {
            get {
                return this.contPrefCodeField;
            }
            set {
                this.contPrefCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLLDDandHealthProblem {
        
        private int lLDDCatField;
        
        private int primaryLLDDField;
        
        private bool primaryLLDDFieldSpecified;
        
        /// <remarks/>
        public int LLDDCat {
            get {
                return this.lLDDCatField;
            }
            set {
                this.lLDDCatField = value;
            }
        }
        
        /// <remarks/>
        public int PrimaryLLDD {
            get {
                return this.primaryLLDDField;
            }
            set {
                this.primaryLLDDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrimaryLLDDSpecified {
            get {
                return this.primaryLLDDFieldSpecified;
            }
            set {
                this.primaryLLDDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearnerFAM {
        
        private string learnFAMTypeField;
        
        private int learnFAMCodeField;
        
        /// <remarks/>
        public string LearnFAMType {
            get {
                return this.learnFAMTypeField;
            }
            set {
                this.learnFAMTypeField = value;
            }
        }
        
        /// <remarks/>
        public int LearnFAMCode {
            get {
                return this.learnFAMCodeField;
            }
            set {
                this.learnFAMCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerProviderSpecLearnerMonitoring {
        
        private string provSpecLearnMonOccurField;
        
        private string provSpecLearnMonField;
        
        /// <remarks/>
        public string ProvSpecLearnMonOccur {
            get {
                return this.provSpecLearnMonOccurField;
            }
            set {
                this.provSpecLearnMonOccurField = value;
            }
        }
        
        /// <remarks/>
        public string ProvSpecLearnMon {
            get {
                return this.provSpecLearnMonField;
            }
            set {
                this.provSpecLearnMonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearnerEmploymentStatus {
        
        private int empStatField;
        
        private System.DateTime dateEmpStatAppField;
        
        private int empIdField;
        
        private bool empIdFieldSpecified;
        
        private string agreeIdField;
        
        private MessageLearnerLearnerEmploymentStatusEmploymentStatusMonitoring[] employmentStatusMonitoringField;
        
        /// <remarks/>
        public int EmpStat {
            get {
                return this.empStatField;
            }
            set {
                this.empStatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateEmpStatApp {
            get {
                return this.dateEmpStatAppField;
            }
            set {
                this.dateEmpStatAppField = value;
            }
        }
        
        /// <remarks/>
        public int EmpId {
            get {
                return this.empIdField;
            }
            set {
                this.empIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmpIdSpecified {
            get {
                return this.empIdFieldSpecified;
            }
            set {
                this.empIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string AgreeId {
            get {
                return this.agreeIdField;
            }
            set {
                this.agreeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmploymentStatusMonitoring")]
        public MessageLearnerLearnerEmploymentStatusEmploymentStatusMonitoring[] EmploymentStatusMonitoring {
            get {
                return this.employmentStatusMonitoringField;
            }
            set {
                this.employmentStatusMonitoringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearnerEmploymentStatusEmploymentStatusMonitoring {
        
        private string eSMTypeField;
        
        private int eSMCodeField;
        
        /// <remarks/>
        public string ESMType {
            get {
                return this.eSMTypeField;
            }
            set {
                this.eSMTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ESMCode {
            get {
                return this.eSMCodeField;
            }
            set {
                this.eSMCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearnerHE {
        
        private string uCASPERIDField;
        
        private int tTACCOMField;
        
        private bool tTACCOMFieldSpecified;
        
        private MessageLearnerLearnerHELearnerHEFinancialSupport[] learnerHEFinancialSupportField;
        
        /// <remarks/>
        public string UCASPERID {
            get {
                return this.uCASPERIDField;
            }
            set {
                this.uCASPERIDField = value;
            }
        }
        
        /// <remarks/>
        public int TTACCOM {
            get {
                return this.tTACCOMField;
            }
            set {
                this.tTACCOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TTACCOMSpecified {
            get {
                return this.tTACCOMFieldSpecified;
            }
            set {
                this.tTACCOMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LearnerHEFinancialSupport")]
        public MessageLearnerLearnerHELearnerHEFinancialSupport[] LearnerHEFinancialSupport {
            get {
                return this.learnerHEFinancialSupportField;
            }
            set {
                this.learnerHEFinancialSupportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearnerHELearnerHEFinancialSupport {
        
        private int fINTYPEField;
        
        private int fINAMOUNTField;
        
        /// <remarks/>
        public int FINTYPE {
            get {
                return this.fINTYPEField;
            }
            set {
                this.fINTYPEField = value;
            }
        }
        
        /// <remarks/>
        public int FINAMOUNT {
            get {
                return this.fINAMOUNTField;
            }
            set {
                this.fINAMOUNTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearningDelivery {
        
        private string learnAimRefField;
        
        private int aimTypeField;
        
        private int aimSeqNumberField;
        
        private System.DateTime learnStartDateField;
        
        private System.DateTime origLearnStartDateField;
        
        private bool origLearnStartDateFieldSpecified;
        
        private System.DateTime learnPlanEndDateField;
        
        private int fundModelField;
        
        private int progTypeField;
        
        private bool progTypeFieldSpecified;
        
        private int fworkCodeField;
        
        private bool fworkCodeFieldSpecified;
        
        private int pwayCodeField;
        
        private bool pwayCodeFieldSpecified;
        
        private int stdCodeField;
        
        private bool stdCodeFieldSpecified;
        
        private int partnerUKPRNField;
        
        private bool partnerUKPRNFieldSpecified;
        
        private string delLocPostCodeField;
        
        private int addHoursField;
        
        private bool addHoursFieldSpecified;
        
        private int priorLearnFundAdjField;
        
        private bool priorLearnFundAdjFieldSpecified;
        
        private int otherFundAdjField;
        
        private bool otherFundAdjFieldSpecified;
        
        private string conRefNumberField;
        
        private string ePAOrgIDField;
        
        private int empOutcomeField;
        
        private bool empOutcomeFieldSpecified;
        
        private int compStatusField;
        
        private System.DateTime learnActEndDateField;
        
        private bool learnActEndDateFieldSpecified;
        
        private int withdrawReasonField;
        
        private bool withdrawReasonFieldSpecified;
        
        private int outcomeField;
        
        private bool outcomeFieldSpecified;
        
        private System.DateTime achDateField;
        
        private bool achDateFieldSpecified;
        
        private string outGradeField;
        
        private string sWSupAimIdField;
        
        private MessageLearnerLearningDeliveryLearningDeliveryFAM[] learningDeliveryFAMField;
        
        private MessageLearnerLearningDeliveryLearningDeliveryWorkPlacement[] learningDeliveryWorkPlacementField;
        
        private MessageLearnerLearningDeliveryAppFinRecord[] appFinRecordField;
        
        private MessageLearnerLearningDeliveryProviderSpecDeliveryMonitoring[] providerSpecDeliveryMonitoringField;
        
        private MessageLearnerLearningDeliveryLearningDeliveryHE learningDeliveryHEField;
        
        /// <remarks/>
        public string LearnAimRef {
            get {
                return this.learnAimRefField;
            }
            set {
                this.learnAimRefField = value;
            }
        }
        
        /// <remarks/>
        public int AimType {
            get {
                return this.aimTypeField;
            }
            set {
                this.aimTypeField = value;
            }
        }
        
        /// <remarks/>
        public int AimSeqNumber {
            get {
                return this.aimSeqNumberField;
            }
            set {
                this.aimSeqNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LearnStartDate {
            get {
                return this.learnStartDateField;
            }
            set {
                this.learnStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime OrigLearnStartDate {
            get {
                return this.origLearnStartDateField;
            }
            set {
                this.origLearnStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrigLearnStartDateSpecified {
            get {
                return this.origLearnStartDateFieldSpecified;
            }
            set {
                this.origLearnStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LearnPlanEndDate {
            get {
                return this.learnPlanEndDateField;
            }
            set {
                this.learnPlanEndDateField = value;
            }
        }
        
        /// <remarks/>
        public int FundModel {
            get {
                return this.fundModelField;
            }
            set {
                this.fundModelField = value;
            }
        }
        
        /// <remarks/>
        public int ProgType {
            get {
                return this.progTypeField;
            }
            set {
                this.progTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProgTypeSpecified {
            get {
                return this.progTypeFieldSpecified;
            }
            set {
                this.progTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int FworkCode {
            get {
                return this.fworkCodeField;
            }
            set {
                this.fworkCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FworkCodeSpecified {
            get {
                return this.fworkCodeFieldSpecified;
            }
            set {
                this.fworkCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PwayCode {
            get {
                return this.pwayCodeField;
            }
            set {
                this.pwayCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PwayCodeSpecified {
            get {
                return this.pwayCodeFieldSpecified;
            }
            set {
                this.pwayCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int StdCode {
            get {
                return this.stdCodeField;
            }
            set {
                this.stdCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StdCodeSpecified {
            get {
                return this.stdCodeFieldSpecified;
            }
            set {
                this.stdCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PartnerUKPRN {
            get {
                return this.partnerUKPRNField;
            }
            set {
                this.partnerUKPRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartnerUKPRNSpecified {
            get {
                return this.partnerUKPRNFieldSpecified;
            }
            set {
                this.partnerUKPRNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DelLocPostCode {
            get {
                return this.delLocPostCodeField;
            }
            set {
                this.delLocPostCodeField = value;
            }
        }
        
        /// <remarks/>
        public int AddHours {
            get {
                return this.addHoursField;
            }
            set {
                this.addHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddHoursSpecified {
            get {
                return this.addHoursFieldSpecified;
            }
            set {
                this.addHoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PriorLearnFundAdj {
            get {
                return this.priorLearnFundAdjField;
            }
            set {
                this.priorLearnFundAdjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriorLearnFundAdjSpecified {
            get {
                return this.priorLearnFundAdjFieldSpecified;
            }
            set {
                this.priorLearnFundAdjFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int OtherFundAdj {
            get {
                return this.otherFundAdjField;
            }
            set {
                this.otherFundAdjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OtherFundAdjSpecified {
            get {
                return this.otherFundAdjFieldSpecified;
            }
            set {
                this.otherFundAdjFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ConRefNumber {
            get {
                return this.conRefNumberField;
            }
            set {
                this.conRefNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EPAOrgID {
            get {
                return this.ePAOrgIDField;
            }
            set {
                this.ePAOrgIDField = value;
            }
        }
        
        /// <remarks/>
        public int EmpOutcome {
            get {
                return this.empOutcomeField;
            }
            set {
                this.empOutcomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmpOutcomeSpecified {
            get {
                return this.empOutcomeFieldSpecified;
            }
            set {
                this.empOutcomeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int CompStatus {
            get {
                return this.compStatusField;
            }
            set {
                this.compStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LearnActEndDate {
            get {
                return this.learnActEndDateField;
            }
            set {
                this.learnActEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LearnActEndDateSpecified {
            get {
                return this.learnActEndDateFieldSpecified;
            }
            set {
                this.learnActEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int WithdrawReason {
            get {
                return this.withdrawReasonField;
            }
            set {
                this.withdrawReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WithdrawReasonSpecified {
            get {
                return this.withdrawReasonFieldSpecified;
            }
            set {
                this.withdrawReasonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Outcome {
            get {
                return this.outcomeField;
            }
            set {
                this.outcomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OutcomeSpecified {
            get {
                return this.outcomeFieldSpecified;
            }
            set {
                this.outcomeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime AchDate {
            get {
                return this.achDateField;
            }
            set {
                this.achDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AchDateSpecified {
            get {
                return this.achDateFieldSpecified;
            }
            set {
                this.achDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OutGrade {
            get {
                return this.outGradeField;
            }
            set {
                this.outGradeField = value;
            }
        }
        
        /// <remarks/>
        public string SWSupAimId {
            get {
                return this.sWSupAimIdField;
            }
            set {
                this.sWSupAimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LearningDeliveryFAM")]
        public MessageLearnerLearningDeliveryLearningDeliveryFAM[] LearningDeliveryFAM {
            get {
                return this.learningDeliveryFAMField;
            }
            set {
                this.learningDeliveryFAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LearningDeliveryWorkPlacement")]
        public MessageLearnerLearningDeliveryLearningDeliveryWorkPlacement[] LearningDeliveryWorkPlacement {
            get {
                return this.learningDeliveryWorkPlacementField;
            }
            set {
                this.learningDeliveryWorkPlacementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AppFinRecord")]
        public MessageLearnerLearningDeliveryAppFinRecord[] AppFinRecord {
            get {
                return this.appFinRecordField;
            }
            set {
                this.appFinRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProviderSpecDeliveryMonitoring")]
        public MessageLearnerLearningDeliveryProviderSpecDeliveryMonitoring[] ProviderSpecDeliveryMonitoring {
            get {
                return this.providerSpecDeliveryMonitoringField;
            }
            set {
                this.providerSpecDeliveryMonitoringField = value;
            }
        }
        
        /// <remarks/>
        public MessageLearnerLearningDeliveryLearningDeliveryHE LearningDeliveryHE {
            get {
                return this.learningDeliveryHEField;
            }
            set {
                this.learningDeliveryHEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearningDeliveryLearningDeliveryFAM {
        
        private string learnDelFAMTypeField;
        
        private string learnDelFAMCodeField;
        
        private System.DateTime learnDelFAMDateFromField;
        
        private bool learnDelFAMDateFromFieldSpecified;
        
        private System.DateTime learnDelFAMDateToField;
        
        private bool learnDelFAMDateToFieldSpecified;
        
        /// <remarks/>
        public string LearnDelFAMType {
            get {
                return this.learnDelFAMTypeField;
            }
            set {
                this.learnDelFAMTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LearnDelFAMCode {
            get {
                return this.learnDelFAMCodeField;
            }
            set {
                this.learnDelFAMCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LearnDelFAMDateFrom {
            get {
                return this.learnDelFAMDateFromField;
            }
            set {
                this.learnDelFAMDateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LearnDelFAMDateFromSpecified {
            get {
                return this.learnDelFAMDateFromFieldSpecified;
            }
            set {
                this.learnDelFAMDateFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LearnDelFAMDateTo {
            get {
                return this.learnDelFAMDateToField;
            }
            set {
                this.learnDelFAMDateToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LearnDelFAMDateToSpecified {
            get {
                return this.learnDelFAMDateToFieldSpecified;
            }
            set {
                this.learnDelFAMDateToFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearningDeliveryLearningDeliveryWorkPlacement {
        
        private System.DateTime workPlaceStartDateField;
        
        private System.DateTime workPlaceEndDateField;
        
        private bool workPlaceEndDateFieldSpecified;
        
        private int workPlaceHoursField;
        
        private int workPlaceModeField;
        
        private int workPlaceEmpIdField;
        
        private bool workPlaceEmpIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime WorkPlaceStartDate {
            get {
                return this.workPlaceStartDateField;
            }
            set {
                this.workPlaceStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime WorkPlaceEndDate {
            get {
                return this.workPlaceEndDateField;
            }
            set {
                this.workPlaceEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorkPlaceEndDateSpecified {
            get {
                return this.workPlaceEndDateFieldSpecified;
            }
            set {
                this.workPlaceEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int WorkPlaceHours {
            get {
                return this.workPlaceHoursField;
            }
            set {
                this.workPlaceHoursField = value;
            }
        }
        
        /// <remarks/>
        public int WorkPlaceMode {
            get {
                return this.workPlaceModeField;
            }
            set {
                this.workPlaceModeField = value;
            }
        }
        
        /// <remarks/>
        public int WorkPlaceEmpId {
            get {
                return this.workPlaceEmpIdField;
            }
            set {
                this.workPlaceEmpIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorkPlaceEmpIdSpecified {
            get {
                return this.workPlaceEmpIdFieldSpecified;
            }
            set {
                this.workPlaceEmpIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearningDeliveryAppFinRecord {
        
        private string aFinTypeField;
        
        private int aFinCodeField;
        
        private System.DateTime aFinDateField;
        
        private int aFinAmountField;
        
        /// <remarks/>
        public string AFinType {
            get {
                return this.aFinTypeField;
            }
            set {
                this.aFinTypeField = value;
            }
        }
        
        /// <remarks/>
        public int AFinCode {
            get {
                return this.aFinCodeField;
            }
            set {
                this.aFinCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime AFinDate {
            get {
                return this.aFinDateField;
            }
            set {
                this.aFinDateField = value;
            }
        }
        
        /// <remarks/>
        public int AFinAmount {
            get {
                return this.aFinAmountField;
            }
            set {
                this.aFinAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearningDeliveryProviderSpecDeliveryMonitoring {
        
        private string provSpecDelMonOccurField;
        
        private string provSpecDelMonField;
        
        /// <remarks/>
        public string ProvSpecDelMonOccur {
            get {
                return this.provSpecDelMonOccurField;
            }
            set {
                this.provSpecDelMonOccurField = value;
            }
        }
        
        /// <remarks/>
        public string ProvSpecDelMon {
            get {
                return this.provSpecDelMonField;
            }
            set {
                this.provSpecDelMonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerLearningDeliveryLearningDeliveryHE {
        
        private string nUMHUSField;
        
        private string sSNField;
        
        private string qUALENT3Field;
        
        private int sOC2000Field;
        
        private bool sOC2000FieldSpecified;
        
        private int sECField;
        
        private bool sECFieldSpecified;
        
        private string uCASAPPIDField;
        
        private int tYPEYRField;
        
        private int mODESTUDField;
        
        private int fUNDLEVField;
        
        private int fUNDCOMPField;
        
        private decimal sTULOADField;
        
        private bool sTULOADFieldSpecified;
        
        private int yEARSTUField;
        
        private int mSTUFEEField;
        
        private decimal pCOLABField;
        
        private bool pCOLABFieldSpecified;
        
        private decimal pCFLDCSField;
        
        private bool pCFLDCSFieldSpecified;
        
        private decimal pCSLDCSField;
        
        private bool pCSLDCSFieldSpecified;
        
        private decimal pCTLDCSField;
        
        private bool pCTLDCSFieldSpecified;
        
        private int sPECFEEField;
        
        private int nETFEEField;
        
        private bool nETFEEFieldSpecified;
        
        private int gROSSFEEField;
        
        private bool gROSSFEEFieldSpecified;
        
        private string dOMICILEField;
        
        private int eLQField;
        
        private bool eLQFieldSpecified;
        
        private string hEPostCodeField;
        
        /// <remarks/>
        public string NUMHUS {
            get {
                return this.nUMHUSField;
            }
            set {
                this.nUMHUSField = value;
            }
        }
        
        /// <remarks/>
        public string SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
            }
        }
        
        /// <remarks/>
        public string QUALENT3 {
            get {
                return this.qUALENT3Field;
            }
            set {
                this.qUALENT3Field = value;
            }
        }
        
        /// <remarks/>
        public int SOC2000 {
            get {
                return this.sOC2000Field;
            }
            set {
                this.sOC2000Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SOC2000Specified {
            get {
                return this.sOC2000FieldSpecified;
            }
            set {
                this.sOC2000FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SEC {
            get {
                return this.sECField;
            }
            set {
                this.sECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SECSpecified {
            get {
                return this.sECFieldSpecified;
            }
            set {
                this.sECFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string UCASAPPID {
            get {
                return this.uCASAPPIDField;
            }
            set {
                this.uCASAPPIDField = value;
            }
        }
        
        /// <remarks/>
        public int TYPEYR {
            get {
                return this.tYPEYRField;
            }
            set {
                this.tYPEYRField = value;
            }
        }
        
        /// <remarks/>
        public int MODESTUD {
            get {
                return this.mODESTUDField;
            }
            set {
                this.mODESTUDField = value;
            }
        }
        
        /// <remarks/>
        public int FUNDLEV {
            get {
                return this.fUNDLEVField;
            }
            set {
                this.fUNDLEVField = value;
            }
        }
        
        /// <remarks/>
        public int FUNDCOMP {
            get {
                return this.fUNDCOMPField;
            }
            set {
                this.fUNDCOMPField = value;
            }
        }
        
        /// <remarks/>
        public decimal STULOAD {
            get {
                return this.sTULOADField;
            }
            set {
                this.sTULOADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STULOADSpecified {
            get {
                return this.sTULOADFieldSpecified;
            }
            set {
                this.sTULOADFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int YEARSTU {
            get {
                return this.yEARSTUField;
            }
            set {
                this.yEARSTUField = value;
            }
        }
        
        /// <remarks/>
        public int MSTUFEE {
            get {
                return this.mSTUFEEField;
            }
            set {
                this.mSTUFEEField = value;
            }
        }
        
        /// <remarks/>
        public decimal PCOLAB {
            get {
                return this.pCOLABField;
            }
            set {
                this.pCOLABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PCOLABSpecified {
            get {
                return this.pCOLABFieldSpecified;
            }
            set {
                this.pCOLABFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PCFLDCS {
            get {
                return this.pCFLDCSField;
            }
            set {
                this.pCFLDCSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PCFLDCSSpecified {
            get {
                return this.pCFLDCSFieldSpecified;
            }
            set {
                this.pCFLDCSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PCSLDCS {
            get {
                return this.pCSLDCSField;
            }
            set {
                this.pCSLDCSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PCSLDCSSpecified {
            get {
                return this.pCSLDCSFieldSpecified;
            }
            set {
                this.pCSLDCSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PCTLDCS {
            get {
                return this.pCTLDCSField;
            }
            set {
                this.pCTLDCSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PCTLDCSSpecified {
            get {
                return this.pCTLDCSFieldSpecified;
            }
            set {
                this.pCTLDCSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SPECFEE {
            get {
                return this.sPECFEEField;
            }
            set {
                this.sPECFEEField = value;
            }
        }
        
        /// <remarks/>
        public int NETFEE {
            get {
                return this.nETFEEField;
            }
            set {
                this.nETFEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NETFEESpecified {
            get {
                return this.nETFEEFieldSpecified;
            }
            set {
                this.nETFEEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int GROSSFEE {
            get {
                return this.gROSSFEEField;
            }
            set {
                this.gROSSFEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GROSSFEESpecified {
            get {
                return this.gROSSFEEFieldSpecified;
            }
            set {
                this.gROSSFEEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DOMICILE {
            get {
                return this.dOMICILEField;
            }
            set {
                this.dOMICILEField = value;
            }
        }
        
        /// <remarks/>
        public int ELQ {
            get {
                return this.eLQField;
            }
            set {
                this.eLQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ELQSpecified {
            get {
                return this.eLQFieldSpecified;
            }
            set {
                this.eLQFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string HEPostCode {
            get {
                return this.hEPostCodeField;
            }
            set {
                this.hEPostCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerDestinationandProgression {
        
        private string learnRefNumberField;
        
        private long uLNField;
        
        private MessageLearnerDestinationandProgressionDPOutcome[] dPOutcomeField;
        
        /// <remarks/>
        public string LearnRefNumber {
            get {
                return this.learnRefNumberField;
            }
            set {
                this.learnRefNumberField = value;
            }
        }
        
        /// <remarks/>
        public long ULN {
            get {
                return this.uLNField;
            }
            set {
                this.uLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DPOutcome")]
        public MessageLearnerDestinationandProgressionDPOutcome[] DPOutcome {
            get {
                return this.dPOutcomeField;
            }
            set {
                this.dPOutcomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ESFA/ILR/2018-19")]
    public partial class MessageLearnerDestinationandProgressionDPOutcome {
        
        private string outTypeField;
        
        private int outCodeField;
        
        private System.DateTime outStartDateField;
        
        private System.DateTime outEndDateField;
        
        private bool outEndDateFieldSpecified;
        
        private System.DateTime outCollDateField;
        
        /// <remarks/>
        public string OutType {
            get {
                return this.outTypeField;
            }
            set {
                this.outTypeField = value;
            }
        }
        
        /// <remarks/>
        public int OutCode {
            get {
                return this.outCodeField;
            }
            set {
                this.outCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime OutStartDate {
            get {
                return this.outStartDateField;
            }
            set {
                this.outStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime OutEndDate {
            get {
                return this.outEndDateField;
            }
            set {
                this.outEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OutEndDateSpecified {
            get {
                return this.outEndDateFieldSpecified;
            }
            set {
                this.outEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime OutCollDate {
            get {
                return this.outCollDateField;
            }
            set {
                this.outCollDateField = value;
            }
        }
    }
}
